import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import Header from "@/components/shared/Header";

import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Toaster } from "sonner";
import { ModalProvider } from "@/providers/ModalProvider";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AICTE Curriculum Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <Header />
          <ModalProvider />
          <main className="pt-[80px] h-full">
            {children}
            <Footer />
          </main>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
