import { ConvexClientProvider } from "@/providers/convex-client-provider";
import "@/app/globals.css";
import { ModalProvider } from "@/providers/ModalProvider";

export const metadata = {
  title: "AICTE Curriculum Portal",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          <ModalProvider />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
