import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AICTE Curriculum Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} h-screen flex items-center justify-center`}
        >
          {/* <div className="w-full h-96 absolute bg-[#f7941d]  -z-10 -skew-y-12" /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
